name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Darwin ARM64
      run: DDCGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -installsuffix cgo -tags=jsoniter   -o ./darwin_arm64 main.go

    - name: Build Darwin AMD64
      run: DDCGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -installsuffix cgo -tags=jsoniter   -o ./darwin_amd64 main.go

    - name: Build Linux AMD64
      run: DDCGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -installsuffix cgo -tags=jsoniter   -o ./linux_amd64 main.go

    - name: Build Linux ARMv5
      run: DDCGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5  go build -ldflags="-s -w" -installsuffix cgo -tags=jsoniter   -o ./linux_arm_v5 main.go

    - name: Build Linux ARMv6
      run: DDCGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6  go build -ldflags="-s -w" -installsuffix cgo -tags=jsoniter   -o ./linux_arm_v6 main.go

    - name: Build Linux ARMv7
      run: DDCGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7  go build -ldflags="-s -w" -installsuffix cgo -tags=jsoniter   -o ./linux_arm_v7 main.go

    - name: Build Windows x86
      run: DDCGO_ENABLED=0 GOOS=windows GOARCH=386 go build -ldflags="-s -w" -installsuffix cgo -tags=jsoniter   -o ./windows_x86.exe main.go

    - name: Build Windows x64
      run: DDCGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -installsuffix cgo -tags=jsoniter   -o ./windows_x64.exe main.go

    - name: Automatic Releases
      # You may pin to the exact commit or the version.
      # uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "${{ github.event_name }}"
        title: "client"
        files: |
          darwin_arm64
          darwin_amd64
          linux_amd64
          linux_arm_v5
          linux_arm_v6
          linux_arm_v7
          windows_x86.exe
          windows_x64.exe